### ISSUE TITLE
dub dependency issue?

### ISSUE THREAD

**Issue by profan** [DerelictOrg/DerelictALURE#2]
Hello!

If one requires a package in their project, for example "derelict-al" at a given version, say "~>1.0.1", and this package for example requires it at "~master", you'll end up with a bit of a confusing message along the lines of "root package contains reference to invalid package derelict-al >= 1.0.1 ..."

Might be worth nothing for those who use dub, since having a requirement on derelict-al at a pinned version, and then adding this will result in breakage due to the mismatch in dependencies.

Putting down a note about this might be worth it, to save future users some confusion.

**Comment by aldacron** [comment]
Yes, that's left over from before DUB deprecated branch names as dependencies. This package still has a package.json that hasn't been renamed to dub.json. I've long since updated the others, but this one just slipped through the cracks. Thanks for bringing it to my attention. I'll fix it as soon as I get a chance.

**Comment by profan** [comment]
Awesome, thanks! :+1:

**Comment by aldacron** [comment]
Should be sorted in the newly tagged 1.0.1 release.
